base: &base
  base_path: geocoder
  benchmark: Public_AR_ACS2023
  hostname: geocoding.geo.census.gov
  protocol: https

development:
  <<: *base
  debug: true

production:
  <<: *base

test:
  <<: *base
  debug: true
